#!/bin/bash

#Libraries need a ldconfig

ldconfig

useradd -m pi

gpasswd -a pi video

echo "allowed_users=anybody" > /etc/X11/Xwrapper.config

cp /app/xinitrc /home/pi/.xinitrc;
chown pi: /home/pi/.xinitrc

export DIGITISER_ENDPOINT=${DIGITISER_ENDPOINT:="https://api.bitcoinaverage.com/ticker/global/GBP/"}
export DIGITISER_VALUE_FIELD=${DIGITISER_VALUE_FIELD:="last"}
export DIGITISER_INTERVAL=${DIGITISER_INTERVAL:10}
export DIGITISER_MESSAGE=${DIGITISER_MESSAGE:"You can change this to something more fun."}


sed -i "s|DIGITISER_ENDPOINT|$DIGITISER_ENDPOINT|g" /app/web_assets/index.html
sed -i "s|DIGITISER_VALUE_FIELD|$DIGITISER_VALUE_FIELD|g" /app/web_assets/index.html
sed -i "s|DIGITISER_INTERVAL|$DIGITISER_INTERVAL|g" /app/web_assets/index.html
sed -i "s|DIGITISER_MESSAGE|$DIGITISER_MESSAGE|g" /app/web_assets/index.html

cp /app/web_assets /home/pi/web_assets
chown -R pi: /home/pi/web_assets

su - pi -c startx &
