#!/bin/bash

udevd --daemon
modprobe spi-bcm2708
modprobe fbtft_device name=pitft verbose=0 rotate=90

#Libraries need a ldconfig

ldconfig

useradd -m pi

gpasswd -a pi video

echo "allowed_users=anybody" > /etc/X11/Xwrapper.config

cp /app/xinitrc /home/pi/.xinitrc;
chown pi: /home/pi/.xinitrc

export CLOCK_TZ=${CLOCK_TZ:="-07:00"}

cp -r /app/web_assets /home/pi/web_assets

sync

chown -R pi: /home/pi/web_assets

sync

#su - pi -c startx &
su - pi -c "env FRAMEBUFFER=/dev/fb1 startx &" # Note that this will change if we restart the container
